spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    username: sa
  jpa:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
      orm:
        jdbc:
          bind: trace

custom:
  word: hello
