spring:
  profiles:
    active:
      - common
      - dev

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
      orm:
        jdbc:
          bind: trace

custom:
  word: hello

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3308/board
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:board;mode=mysql
    username: sa
  h2:
    console:
      enabled: true
